import { Prisma } from '@prisma/client';

export const tourSelect = {
  id: true,
  divisionId: true,
  title: true,
  description: true,
  thumbnail: true,
  image: true,
  location: true,
  lat: true,
  lon: true,
  costFrom: true,
  startDate: true,
  endDate: true,
  departureLocation: true,
  arrivalLocation: true,
  included: true,
  excluded: true,
  amenities: true,
  tourPlan: true,
  maxGuest: true,
  minAge: true,
  status: true,
  isDeleted: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.TourSelect;
